sonar.projectKey=alinisar3_cohort-9-mern-10395-ali
sonar.organization=alinisar3
sonar.sources=.
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info,frontend/coverage/lcov.info
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/*.test.js,**/*.test.jsx,**/*.config.*
sonar.coverage.exclusions=**/*.jsx,**/server.js,**/app.js,**/src/config/**,**/src/routes/**,**/src/utils/**,**/src/validations/**,**/src/context/**,**/src/styles/**,**/main.jsx,**/App.jsx