sonar.projectKey=alinisar3_cohort-9-mern-10395-ali
sonar.organization=alinisar3
sonar.sources=.
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**